name: Publish Interface to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Prepare public directory
        run: |
          mkdir -p public
          cp index.html public/ || true
          cp web_interface.html public/ || true
          cp coremap_with_links.svg public/ || true
          cp -R KeyMatrix_DeepGlyph_Engine/deepglyph_panel.html public/ || true
          cp -R *.css public/ || true
          cp -R *.js public/ || true

      - name: Upload to Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2